import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:drift/drift.dart';
import '../../core/database/database_provider.dart';
import '../../core/database/database.dart';

// Note: PacingStat and PacingStatsCompanion are generated by drift.
final pacingStatsProvider = NotifierProvider<PacingStatsNotifier, PacingStat?>(
  () {
    return PacingStatsNotifier();
  },
);

class PacingStatsNotifier extends Notifier<PacingStat?> {
  AppDatabase get _db => ref.read(databaseProvider);

  @override
  PacingStat? build() {
    _init();
    return null;
  }

  Future<void> _init() async {
    final stats = await (_db.select(
      _db.pacingStats,
    )..limit(1)).getSingleOrNull();
    if (stats == null) {
      final newStats = PacingStatsCompanion.insert(
        xp: const Value(0),
        healingLevel: const Value(1),
        currentStreak: const Value(0),
      );
      await _db.into(_db.pacingStats).insert(newStats);
      state = await (_db.select(_db.pacingStats)..limit(1)).getSingle();
    } else {
      state = stats;
    }
  }

  Future<void> addXp(int amount) async {
    if (state == null) return;

    final newXp = state!.xp + amount;
    final newLevel = _calculateLevel(newXp);

    final updated = state!.copyWith(xp: newXp, healingLevel: newLevel);
    await _db.update(_db.pacingStats).replace(updated);
    state = updated;
  }

  Future<void> deductXp(int amount) async {
    if (state == null) return;

    final newXp = (state!.xp - amount).clamp(0, 1000000).toInt();
    final newLevel = _calculateLevel(newXp);

    final updated = state!.copyWith(xp: newXp, healingLevel: newLevel);
    await _db.update(_db.pacingStats).replace(updated);
    state = updated;
  }

  int _calculateLevel(int xp) {
    if (xp < 200) return 1;
    if (xp < 500) return 2;
    if (xp < 900) return 3;
    if (xp < 1400) return 4;
    return (xp / 500).floor() + 1;
  }

  double getLevelProgress(int xp) {
    int currentLevelThreshold = 0;
    int nextLevelThreshold = 200;

    if (xp < 200) {
      currentLevelThreshold = 0;
      nextLevelThreshold = 200;
    } else if (xp < 500) {
      currentLevelThreshold = 200;
      nextLevelThreshold = 500;
    } else if (xp < 900) {
      currentLevelThreshold = 500;
      nextLevelThreshold = 900;
    } else {
      currentLevelThreshold = 900;
      nextLevelThreshold = 1400;
    }

    final progress =
        (xp - currentLevelThreshold) /
        (nextLevelThreshold - currentLevelThreshold);
    return progress.clamp(0.0, 1.0);
  }
}
